<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Version>4.7.3</Version>
		<PackageId>Kysql_Plugin</PackageId>
		<Authors>KIM YONG SU</Authors>
		<Company>tom4712@kakao.com</Company>
		<Product>Kysql_Plugin</Product>
		<Description>오토캐드 플러그인</Description>
		<Copyright>Copyright © 2026 tom4712@kakao.com. All rights reserved.</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Obfuscar.xml" />
		<None Remove="Resources\MenuConfig.txt" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Obfuscar.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\MenuConfig.txt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DotSpatial.Projections" Version="4.0.656" />
		<PackageReference Include="GeoAPI" Version="1.7.5" />
		<PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022">
			<EmbedInteropTypes>true</EmbedInteropTypes>
		</PackageReference>
		<PackageReference Include="NetTopologySuite" Version="2.6.0" />
		<PackageReference Include="NetTopologySuite.IO.ShapeFile" Version="2.1.0" />
		<PackageReference Include="Obfuscar" Version="2.2.50">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ProjNET4GeoAPI" Version="1.4.1" />
		<PackageReference Include="WPF-UI" Version="4.2.1">
			<GeneratePathProperty>True</GeneratePathProperty>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="AcCoreMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\AcCoreMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcDbMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\AcDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\AcMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AdWindows">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\AdWindows.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
		<Copy SourceFiles="C:\Program Files\Autodesk\AutoCAD 2026\Acdbmgd.dll;C:\Program Files\Autodesk\AutoCAD 2026\AcMgd.dll;C:\Program Files\Autodesk\AutoCAD 2026\AcCoreMgd.dll" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
		<Exec Command="cd &quot;$(TargetDir)&quot; &amp;&amp; &quot;$(PkgObfuscar)\tools\Obfuscar.Console.exe&quot; &quot;$(ProjectDir)Obfuscar.xml&quot;" />
		<Delete Files="$(TargetDir)Acdbmgd.dll;$(TargetDir)AcMgd.dll;$(TargetDir)AcCoreMgd.dll" />
	</Target>
</Project>